const list = [
  {
    id: 11,
    title: "Bread",
    author: "Bread: Staple food made from flour, water, yeast, and salt, baked to create various shapes and textures.",
    price: 2.50,
    img: "https://upload.wikimedia.org/wikipedia/commons/3/33/Fresh_made_bread_05.jpg",
    amount: 1,
    // i need to clearfy how i am going to put the prices down for the differnt retail consumers
  },
  {
    id: 2,
    title: "Milk",
    author: "Milk: Nutrient-rich, white liquid produced by mammals, commonly consumed as a beverage and used in cooking.",
    price: 2,
    img: "https://media.post.rvohealth.io/wp-content/uploads/2022/05/soy-milk-bottle-732-549-feature-thumb-732x549.jpg",
    amount: 1,
  },
  // {
  //   id: 3,
  //   title: "Banana",
  //   author: "Banana: Yellow fruit with soft, sweet flesh, rich in potassium, commonly eaten raw or used in cooking.",
  //   price: 0.90,
  //   img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Cavendish_Banana_DS.jpg/640px-Cavendish_Banana_DS.jpg",
  //   amount: 1,
  // },
  // {
  //   id: 4,
  //   title: "Apple",
  //   author: "Apple: Round fruit with crisp flesh, typically red, green, or yellow, widely enjoyed fresh or in cooking.",
  //   price: 1.20,
  //   img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/1200px-Red_Apple.jpg",
  //   amount: 1,
  // },
  {
    id: 5,
    title: "Eggs",
    author: "Egg: Versatile culinary ingredient, with a shell enclosing a yolk and white, commonly used in cooking and baking.",
    price: 2,
    img: "https://kidseatincolor.com/wp-content/uploads/2022/02/eggs-e1648216350119-500x500.jpeg",
    amount: 1,
  },
//   {
//     id: 6,
//     title: "Chicken",
//     author: "Chicken meat: Common poultry meat, versatile in cooking, relatively lean with a mild flavor, widely consumed worldwide.",
//     price: 8,
//     img: "https://www.shutterstock.com/image-photo/fresh-raw-chicken-isolated-on-600nw-583587001.jpg",
//     amount: 1,
//   },
//   {
//     id: 7,
//     title: "Toilet paper",
//     author: "Toilet paper: Soft paper product used for personal hygiene, typically in bathroom settings for cleaning after defecation.",
//     price: 5,
//     img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Toiletpapier_%28Gobran111%29.jpg/1200px-Toiletpapier_%28Gobran111%29.jpg",
//     amount: 1,
//   },
//   {
//     id: 8,
//     title: "Toothpaste",
//     author: "Toothpaste: Oral hygiene product applied to a toothbrush to clean teeth, prevent cavities, and freshen breath.",
//     price: 1.49,
//     img: "https://www.surbitondental.co.uk/wp-content/uploads/2017/11/toothpaste.jpg",
//     amount: 1,
//   },
//   {
//     id: 9,
//     title: "Naan bread",
//     author: "Naan bread: Soft, leavened flatbread originating from the Indian subcontinent, often served with curries or grilled meats.",
//     price: 5.99,
//     img: "https://media.chefdehome.com/740/0/0/baked-naan/easy-homemade-oven-baked-naan-chefdehome-3.jpg",
//     amount: 1,
//   },
//   {
//     id: 10,
//     title: "Pizza",
//     author: "Pizza: Iconic Italian dish, consisting of a flattened dough topped with tomato sauce, cheese, and various toppings, baked.",
//     price: 3.5,
//     img: "https://www.foodandwine.com/thmb/Wd4lBRZz3X_8qBr69UOu2m7I2iw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/classic-cheese-pizza-FT-RECIPE0422-31a2c938fc2546c9a07b7011658cfd05.jpg",
//     amount: 1,
//   },
//   {
//     id: 11,
//     title: "Patato",
//     author: "Potato: Starchy tuberous crop, widely cultivated worldwide, versatile in cooking, and a staple in many cuisines.",
//     price: 5.5,
//     img: "https://media.istockphoto.com/id/157430678/photo/three-potatoes.jpg?s=612x612&w=0&k=20&c=qkMoEgcj8ZvYbzDYEJEhbQ57v-nmkHS7e88q8dv7TSA=",
//     amount: 1,
//   },
//   {
//     id: 12,
//     title: "Pasta",
//     author: "Pasta: Versatile, dough-based dish, often made from wheat flour, water, and sometimes eggs, served cooked.",
//     price: 2.90,
//     img: "https://5.imimg.com/data5/FC/XO/OI/SELLER-73131336/penne-500x500.jpg",
//     amount: 1,
//   },
];

export default list;
